import {StyleSheet} from 'react-native';
import {Directions} from 'react-native-gesture-handler';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dottedLineContainer: {
    flex: 0.7,
    alignItems: 'center',
    position: 'relative',
    top: 6,
  },
  dottedLine: {
    borderBottomWidth: 2,
    borderBottomColor: '#27aae2',
    width: '80%',
    borderStyle: 'dotted',
  },

  blueDot: {
    position: 'absolute',
    top: -2,
    right: '50%',
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'red',
  },
  mainView: {
    flexDirection: 'row',
  },
  price: {
    position: 'absolute',
    left: 12,
    top: 12,
  },
  from: {
    flexDirection: 'column',
    marginLeft: 15,
    marginTop: 16,
  },
  to: {flexDirection: 'column', marginTop: 16},
  stopAir: {
    marginTop: 9,
  },
  outboundContainer: {
    flexDirection: 'column',
    borderRadius: 5,
    margin: 10,
    paddingBottom: 10,
    paddingTop: 10,
    backgroundColor: 'white',
  },
  airline: {
    marginTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#F3F3F3',
  },
  favbutton: {
    flexDirection: 'row',
    // backgroundColor: 'red',
    justifyContent: 'space-between',
  },
  airlineb: {
    marginLeft: 15,
  },
  Text: {
    fontWeight: 'bold',
    fontSize: 14,
  },
  priceText: {
    fontWeight: 'bold',
    fontSize: 20,
  },
  bag: {
    borderBottomWidth: 1,
    borderBottomColor: '#F3F3F3',
    marginBottom: 20,
  },
  fontSize: {
    fontSize: 10,
  },
  HomePage: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderBottomWidth: 1,
    borderBottomColor: '#E3E3E3',
    margin: 10,
  },
  PressedButton: {
    borderBottomWidth: 1,
    borderBottomColor: '#27aae2',
  },
  HomePageTabsText: {
    fontSize: 18,
    margin: 10,
    fontWeight: 'bold',
  },
  dateInput: {
    flexDirection: 'row',
    margin: 10,
    marginTop: 20,
    borderWidth: 0.5,
    borderRadius: 8,
    borderColor: '#27aae2',
    justifyContent: 'space-evenly',
    backgroundColor: 'white',
  },
  modalPage: {
    backgroundColor: 'white',
    marginTop: 350,
  },
  destinationFrom: {
    borderWidth: 0.5,
    marginLeft: 10,
    marginRight: 10,
    borderColor: '#27aae2',
    backgroundColor: 'white',
    borderTopRightRadius: 8,
    borderTopLeftRadius: 8,
    margin: 1.5,
    fontSize: 16,
  },
  destinationTo: {
    borderWidth: 0.5,
    marginLeft: 10,
    marginRight: 10,
    borderColor: '#27aae2',
    backgroundColor: 'white',
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    margin: 1.5,
    fontSize: 16,
  },
  textBold: {
    fontWeight: 'bold',
  },
  buttonsF: {
    padding: 8,
    fontSize: 18,
    borderWidth: 0.5,
    borderColor: '#27aae2',
    marginTop: 30,
    width: '100%',
    textAlign: 'center',
    fontWeight: 'bold',
    backgroundColor: '#27aae2',
    marginRight: 150,
    borderBottomLeftRadius: 8,
    borderTopLeftRadius: 8,
    color: 'white',
  },
  buttonsS: {
    padding: 8,
    fontSize: 18,
    borderWidth: 0.5,
    borderColor: '#27aae2',
    marginTop: 30,
    width: '100%',
    textAlign: 'center',
    fontWeight: 'bold',
    backgroundColor: '#EC7063',
    borderBottomRightRadius: 8,
    borderTopRightRadius: 8,
    color: 'white',
  },
  switch: {
    width: 40,
    height: 40,
    backgroundColor: 'white',
    position: 'absolute',
    bottom: 33,
    right: 30,
    fontSize: 30,
    textAlign: 'center',
  },
  airlineItem: {
    backgroundColor: 'white',
    marginLeft: 10,
    marginRight: 10,
    padding: 10,
    marginBottom: 10,
    borderRadius: 8,
  },
  airlineText: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  airlineList: {
    backgroundColor: '#F3F3F3',
    marginTop: 400,
  },
  airlineTextHeader: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
    fontWeight: 'bold',
    color: 'white',
  },
  cancelAirlineToggle: {
    fontSize: 16,
    textAlign: 'center',
    fontWeight: 'bold',
    padding: 8,
    backgroundColor: '#59CAFA',
    color: 'white',
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  filterHeaderA: {
    fontSize: 16,
    fontWeight: 'bold',
    backgroundColor: '#27aae2',
    padding: 10,
    width: 121,
    textAlign: 'center',
    borderBottomLeftRadius: 8,
    borderTopLeftRadius: 8,
    color: 'white',
  },
  filterHeaderD: {
    fontSize: 16,
    fontWeight: 'bold',
    backgroundColor: '#27aae2',
    padding: 10,
    width: 121,
    textAlign: 'center',
    color: 'white',
  },
  filterHeaderS: {
    fontSize: 16,
    fontWeight: 'bold',
    backgroundColor: '#27aae2',
    padding: 10,
    width: 121,
    textAlign: 'center',
    borderBottomRightRadius: 8,
    borderTopRightRadius: 8,
    color: 'white',
  },
  filterResults: {
    fontSize: 16,
    fontWeight: 'bold',
    padding: 5,
  },
  dottedLineContainerD: {
    flexDirection: 'column',
    borderLeftWidth: 2,
    marginLeft: 30,
    borderStyle: 'dotted',
    borderColor: '#27aae2',
  },
  flightDetailsInfo: {
    margin: 10,
    fontWeight: 'bold',
    fontSize: 16,
  },
  bluedotInfo: {
    position: 'absolute',
    left: -5.5,
    width: 8,
    height: 8,
    borderRadius: 3,
    backgroundColor: 'red',
  },
  blueDotR: {
    position: 'absolute',
    top: -2,
    right: '45%',
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'red',
  },
  blueDotB: {
    position: 'absolute',
    top: -2,
    right: '55%',
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'red',
  },
});
