(europeanCountriesWithAirports = [
  {
    country: "United Kingdom",
    airport: "Heathrow Airport",
    capitalCity: "London",
  },
  { country: "Germany", airport: "Frankfurt Airport", capitalCity: "Berlin" },
  {
    country: "France",
    airport: "Charles de Gaulle Airport",
    capitalCity: "Paris",
  },
  {
    country: "Spain",
    airport: "Madrid-Barajas Airport",
    capitalCity: "Madrid",
  },
  {
    country: "Portugal",
    airport: "Lisbon Portela Airport",
    capitalCity: "Lisbon",
  },
  {
    country: "Italy",
    airport: "Leonardo da Vinci-Fiumicino Airport",
    capitalCity: "Rome",
  },
  {
    country: "Netherlands",
    airport: "Amsterdam Airport Schiphol",
    capitalCity: "Amsterdam",
  },
  { country: "Belgium", airport: "Brussels Airport", capitalCity: "Brussels" },
  { country: "Switzerland", airport: "Zurich Airport", capitalCity: "Bern" },
  {
    country: "Austria",
    airport: "Vienna International Airport",
    capitalCity: "Vienna",
  },
  {
    country: "Norway",
    airport: "Oslo Gardermoen Airport",
    capitalCity: "Oslo",
  },
  {
    country: "Sweden",
    airport: "Stockholm Arlanda Airport",
    capitalCity: "Stockholm",
  },
  {
    country: "Denmark",
    airport: "Copenhagen Airport",
    capitalCity: "Copenhagen",
  },
  {
    country: "Finland",
    airport: "Helsinki-Vantaa Airport",
    capitalCity: "Helsinki",
  },
  { country: "Ireland", airport: "Dublin Airport", capitalCity: "Dublin" },
  {
    country: "Greece",
    airport: "Athens International Airport",
    capitalCity: "Athens",
  },
  {
    country: "Poland",
    airport: "Warsaw Chopin Airport",
    capitalCity: "Warsaw",
  },
  {
    country: "Czech Republic",
    airport: "Prague Václav Havel Airport",
    capitalCity: "Prague",
  },
  {
    country: "Hungary",
    airport: "Budapest Ferenc Liszt International Airport",
    capitalCity: "Budapest",
  },
  {
    country: "Slovakia",
    airport: "Bratislava Airport",
    capitalCity: "Bratislava",
  },
  {
    country: "Slovenia",
    airport: "Ljubljana Jože Pučnik Airport",
    capitalCity: "Ljubljana",
  },
  { country: "Croatia", airport: "Zagreb Airport", capitalCity: "Zagreb" },
  {
    country: "Bosnia and Herzegovina",
    airport: "Sarajevo International Airport",
    capitalCity: "Sarajevo",
  },
  {
    country: "Serbia",
    airport: "Belgrade Nikola Tesla Airport",
    capitalCity: "Belgrade",
  },
  {
    country: "Montenegro",
    airport: "Podgorica Airport",
    capitalCity: "Podgorica",
  },
  {
    country: "Albania",
    airport: "Tirana International Airport",
    capitalCity: "Tirana",
  },
  {
    country: "North Macedonia",
    airport: "Skopje International Airport",
    capitalCity: "Skopje",
  },
  { country: "Bulgaria", airport: "Sofia Airport", capitalCity: "Sofia" },
  {
    country: "Romania",
    airport: "Henri Coandă International Airport",
    capitalCity: "Bucharest",
  },
  {
    country: "Moldova",
    airport: "Chișinău International Airport",
    capitalCity: "Chișinău",
  },
  {
    country: "Ukraine",
    airport: "Boryspil International Airport",
    capitalCity: "Kyiv",
  },
  {
    country: "Belarus",
    airport: "Minsk National Airport",
    capitalCity: "Minsk",
  },
  {
    country: "Estonia",
    airport: "Lennart Meri Tallinn Airport",
    capitalCity: "Tallinn",
  },
  {
    country: "Latvia",
    airport: "Riga International Airport",
    capitalCity: "Riga",
  },
  { country: "Lithuania", airport: "Vilnius Airport", capitalCity: "Vilnius" },
  {
    country: "Iceland",
    airport: "Keflavík International Airport",
    capitalCity: "Reykjavik",
  },
  {
    country: "Luxembourg",
    airport: "Luxembourg Airport",
    capitalCity: "Luxembourg City",
  },
  {
    country: "Malta",
    airport: "Malta International Airport",
    capitalCity: "Valletta",
  },
  {
    country: "Cyprus",
    airport: "Larnaca International Airport",
    capitalCity: "Nicosia",
  },
  {
    country: "Cyprus",
    airport: "Paphos International Airport",
    capitalCity: "Nicosia",
  },
]),
  (airlines = [
    "Delta",
    "United",
    "American Airlines",
    "Southwest",
    "JetBlue",
    "Lufthansa",
    "British Airways",
    "Air France",
    "KLM Royal Dutch Airlines",
    "Ryanair",
    "EasyJet",
    "Finnair",
    "Aer Lingus",
    "Iberia",
    "Alitalia",
    "Austrian Airlines",
    "Swiss International Air Lines",
    "Scandinavian Airlines (SAS)",
    "Turkish Airlines",
    "LOT Polish Airlines",
    "Czech Airlines",
    "Aeroflot",
    "Air Serbia",
    "Croatia Airlines",
    "Wizz Air",
    "Norwegian Air Shuttle",
    "TAP Air Portugal",
    "Air Malta",
    "Cyprus Airways",
    "Aegean Airlines",
    "Olympic Air",
    "Bulgaria Air",
    "Tarom",
    "Ukraine International Airlines",
    "Belavia",
    "Estonian Air",
    "Air Baltic",
    "Air Iceland",
    "Luxair",
    "Icelandair",
    "Pegasus Airlines",
    "Widerøe",
    "Air Dolomiti",
    "Volotea",
    "Eurowings",
    "Brussels Airlines",
  ]);
module.exports = { europeanCountriesWithAirports, airlines };
